spring.datasource.url:  jdbc:mysql://localhost:3306/Video_streaming
spring.datasource.username: root
spring.datasource.password: manager
spring.servlet.multipart.max-file-size: 128MB
spring.servlet.multipart.max-request-size: 128MB
spring.http.multipart.enabled: false